# These are supported funding model platforms

github: # Americanmonks, PurpleSquirrelMedia
patreon: # patreon.com/PurpleSquirrelMedia
ko_fi: # https://ko-fi.com/purplesquirrel
liberapay: # purplesquirrelmedia
